/* eslint-disable no-unused-vars */
export enum PresentationActionType {
  PRESENTATION_SHARED_SUCCESS = 'PRESENTATION_SHARED_SUCCESS',
  NOPRESENTATION_SHARED_SUCCESS = 'NOPRESENTATION_SHARED_SUCCESS',
  PRESENTATION_SHARED_ERROR = 'PRESENTATION_SHARED_ERROR',
  NOPRESENTATION_SHARED_ERROR = 'NOPRESENTATION_SHARED_ERROR',
  RESET_PRESENTATION_STATE = 'RESET_PRESENTATION_STATE'
}
