/* eslint-disable no-unused-vars */
export enum PresentationRequestActionType {
  CREATE_PRESENTATION_REQUEST = 'CREATE_PRESENTATION_REQUEST',
  CREATE_PRESENTATION_REQUEST_SUCCESS = 'CREATE_PRESENTATION_REQUEST_SUCCESS',
  CREATE_PRESENTATION_REQUEST_ERROR = 'CREATE_PRESENTATION_REQUEST_ERROR'
}
